### ISSUE TITLE
Bug in tinystl::string::resize().

### ISSUE THREAD

**Issue by nielswouters** [mendsley/tinystl#12]
The m_last pointer is incremented by a too large number.

m_last += size;
Should be something like:
m_last = m_first + size;

**Comment by Klowner** [comment]
I see this ticket was from a year ago. I ran into a similar issue when trying to reuse a `tinystl::string` and noticed that after `resize(0)`, subsequent `append()` calls just append to the original string, as expected by looking at the source.

Is it supposed to be this way? :confused:

**Comment by mendsley** [comment]
This is now fixed in f6f49782e99e97e63be13469f24d5e1114d9a918
