### ISSUE TITLE
What did 'vector(other).swap(*this);' mean, in vector.h line 151?

### ISSUE THREAD

**Issue by DeathPoem** [mendsley/tinystl#16]
First, thanks for your implement of this tinystl. I really benefit from this repository.
Second, I have some question when reading your code. Would you mind giving me some hints?

1. vector.h line 151
```cpp
template<typename T, typename Alloc>
	inline vector<T, Alloc>& vector<T, Alloc>::operator=(const vector& other) {
		vector(other).swap(*this);
		return *this;
	}
```
copy construct a new vector and swap them ? why not copy directly?

2. traits.h line 33
```cpp
#if defined(__GNUC__)
#	define TINYSTL_TRY_POD_OPTIMIZATION(t) __is_pod(t)
```
what does __is_pod means ? is that std::is_pos?

**Comment by looki** [comment]
Hey, not the author but __is_pod is a GCC inbuilt function that returns true for POD types, that is, types that are "plain old data" - simple C compatible structs with no user constructor, deconstructor etc.

**Comment by DeathPoem** [comment]
@looki thanks.
