### ISSUE TITLE
VS2015 doesn't like tinystl's unordered_set with uint32_t type

### ISSUE THREAD

**Issue by bkaradzic** [mendsley/tinystl#4]
When building this code:
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_gl.h#L740

with VS2015-CTP6 I see following spew:

1>\bx\include\tinystl/unordered_set.h(86): error C2440: 'initializing': cannot convert from 'tinystl::unordered_hash_node<Key,void> ' to 'tinystl::unordered_hash_node<Key,void> **'
1>          with
1>          [
1>              Key=uint32_t
1>          ]
1>  \bx\include\tinystl/unordered_set.h(86): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
1>  \bx\include\tinystl/unordered_set.h(80): note: while compiling class template member function 'tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator>::unordered_set(const tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator> &)'
1>  \bx\include\tinystl/unordered_set.h(101): note: see reference to function template instantiation 'tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator>::unordered_set(const tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator> &)' being compiled
1>  \bx\include\tinystl/unordered_set.h(72): note: while compiling class template member function 'tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator>::unordered_set(void)'
1>  \bgfx\src\renderer_gl.h(993): note: see reference to function template instantiation 'tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator>::unordered_set(void)' being compiled
1>  \bgfx\src\renderer_gl.h(742): note: see reference to class template instantiation 'tinystl::unordered_set<uint32_t,bgfx::TinyStlAllocator>' being compiled
1>\bx\include\tinystl/unordered_set.h(86): error C2227: left of '->next' must point to class/struct/union/generic type
1>  \bx\include\tinystl/unordered_set.h(86): note: type is 'tinystl::unordered_hash_node<Key,void> **'
1>          with
1>          [
1>              Key=uint32_t
1>          ]
1>\bx\include\tinystl/unordered_set.h(87): error C2664: 'tinystl::unordered_hash_node<Key,void>::unordered_hash_node(tinystl::unordered_hash_node<Key,void> &&)': cannot convert argument 1 from 'tinystl::unordered_hash_node<Key,void> *' to 'const uint32_t &'
1>          with
1>          [
1>              Key=uint32_t
1>          ]
1>  \bx\include\tinystl/unordered_set.h(87): note: Reason: cannot convert from 'tinystl::unordered_hash_node<Key,void> *' to 'const uint32_t'
1>          with
1>          [
1>              Key=uint32_t
1>          ]
1>  \bx\include\tinystl/unordered_set.h(87): note: There is no context in which this conversion is possible

**Comment by mendsley** [comment]
Installing 2015 now to check this

**Comment by mendsley** [comment]
Was able to reproduce this (copy ctor issue with set).

**Comment by bkaradzic** [comment]
:+1:
