### ISSUE TITLE
Bug when tinystl::string is used by different allocators.

### ISSUE THREAD

**Issue by bkaradzic** [mendsley/tinystl#5]
I fixed it here:
https://github.com/bkaradzic/bx/blob/master/include/tinystl/string.h

Basically the problem is that linker removes "redundant" code by function name, not by implementation of function (implementation was changing with allocator macro). It must be different type, in order for linker to not remove code.

**Comment by mendsley** [comment]
Interesting. The only reason the allocator was structured that way was to enable easy fwd-decl of sting. E.g. class string. Maybe that's not used as often as I thought it would be, and the allocator cost is too high. I'll look into merging in the templated allocator solution.

**Comment by bkaradzic** [comment]
If you need repro, just put back old string, and then in bgfx use internal allocator and outside of bgfx use default tinystl allocator, and you'll see mismatch on one allocator.
