### ISSUE TITLE
Support inserting elements from the same vector

### ISSUE THREAD

**Issue by OlegOAndreev** [mendsley/tinystl#7]
There are two separate problems with inserting elements from the same vector: reallocation:
`v.push_back(v[0])` when size() == capacity(), and overwriting when inserting into the middle of the vector: `v.insert(v.begin(), v.back())`.

While the behaviour in this cases is not specified by the C++ standard, most popular libraries (VC++ STL, libstdc++, libc++, EASTL) correctly support both of the cases.

tinystl::vector does not support these cases correctly. Do you consider this a problem? If yes, I can prepare a pull-request which fixes it.

**Comment by mendsley** [comment]
If you could prepare a PR that address this issue, I would happily review and merge it!

Thanks!
